# Generated by Django 5.2.1 on 2025-05-28 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='kmexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('exam_date', models.DateField(verbose_name='Дата проведения экзамена')),
                ('image', models.ImageField(upload_to='exam_images/', verbose_name='Задание по экзамену в виде картинки')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('users', models.ManyToManyField(related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, который пишут экзамен')),
            ],
        ),
    ]
